
'use client';

import { useState, useMemo } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Search, Tag, Type, ArrowLeft } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { AuditLog } from '@/lib/audit-log';
import { useLocalStorage } from '@/hooks/use-company';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

type AuditLogAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'IMPORT' | 'LOGOUT';

// Initial logs can be empty as they will be generated by user actions
const initialLogs: AuditLog[] = [];

export default function AuditTrailPage() {
    // Logs are now global, not scoped to the company
    const [logs, setLogs] = useLocalStorage<AuditLog[]>('audit-trail-logs', initialLogs);
    const [searchTerm, setSearchTerm] = useState('');
    const [moduleFilter, setModuleFilter] = useState('all');
    const [actionFilter, setActionFilter] = useState('all');

    const filteredLogs = useMemo(() => {
        return logs.filter(log => {
            const searchMatch = searchTerm.length < 2 ||
                log.user.toLowerCase().includes(searchTerm.toLowerCase()) ||
                log.module.toLowerCase().includes(searchTerm.toLowerCase()) ||
                log.details.toLowerCase().includes(searchTerm.toLowerCase());

            const moduleMatch = moduleFilter === 'all' || log.module === moduleFilter;
            const actionMatch = actionFilter === 'all' || log.action === actionFilter;

            return searchMatch && moduleMatch && actionMatch;
        }).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()); // Sort by most recent
    }, [logs, searchTerm, moduleFilter, actionFilter]);

    const getBadgeVariant = (action: AuditLogAction) => {
        switch (action) {
            case 'CREATE':
            case 'IMPORT':
                return 'default';
            case 'UPDATE':
                return 'secondary';
            case 'DELETE':
                return 'destructive';
            case 'LOGIN':
                return 'outline';
            default:
                return 'secondary';
        }
    }

    const uniqueModules = ['all', ...Array.from(new Set(logs.map(log => log.module)))];
    const uniqueActions = ['all', ...Array.from(new Set(logs.map(log => log.action)))];

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-4">
                <Link href="/utilitarios">
                    <Button variant="outline" size="icon" className="h-8 w-8">
                        <ArrowLeft className="h-4 w-4" />
                        <span className="sr-only">Voltar</span>
                    </Button>
                </Link>
                <div className="space-y-1">
                    <h1 className="text-3xl font-bold tracking-tight font-headline">Trilha de Auditoria</h1>
                    <p className="text-muted-foreground">
                        Acompanhe as mudanças, ações de usuários e modificações de dados no sistema.
                    </p>
                </div>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Registros de Atividade</CardTitle>
                    <CardDescription>Visualize os eventos recentes que ocorreram no sistema.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="flex flex-col sm:flex-row gap-4 mb-4">
                        <div className="relative flex-1">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                            <Input
                                placeholder="Buscar por usuário, módulo ou detalhes..."
                                className="pl-10"
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                            />
                        </div>
                        <div className='flex gap-4'>
                            <Select value={moduleFilter} onValueChange={setModuleFilter}>
                                <SelectTrigger className="w-full sm:w-[180px]">
                                    <Tag className="mr-2 h-4 w-4 text-muted-foreground"/>
                                    <SelectValue placeholder="Módulo" />
                                </SelectTrigger>
                                <SelectContent>
                                    {uniqueModules.map(mod => (
                                        <SelectItem key={mod} value={mod}>{mod === 'all' ? 'Todos os Módulos' : mod}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                            <Select value={actionFilter} onValueChange={setActionFilter}>
                                <SelectTrigger className="w-full sm:w-[180px]">
                                    <Type className="mr-2 h-4 w-4 text-muted-foreground"/>
                                    <SelectValue placeholder="Ação" />
                                </SelectTrigger>
                                <SelectContent>
                                     {uniqueActions.map(act => (
                                        <SelectItem key={act} value={act}>{act === 'all' ? 'Todas as Ações' : act}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                    <div className="rounded-md border">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead className='w-[180px]'>Data/Hora</TableHead>
                                    <TableHead className='w-[200px]'>Usuário</TableHead>
                                    <TableHead className='w-[150px]'>Módulo</TableHead>
                                    <TableHead className='w-[120px]'>Ação</TableHead>
                                    <TableHead>Detalhes</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {filteredLogs.length > 0 ? (
                                    filteredLogs.map(log => (
                                        <TableRow key={log.id}>
                                            <TableCell className="text-muted-foreground text-xs">
                                                {new Date(log.timestamp).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'medium' })}
                                            </TableCell>
                                            <TableCell className="font-medium">{log.user}</TableCell>
                                            <TableCell>{log.module}</TableCell>
                                            <TableCell>
                                                <Badge variant={getBadgeVariant(log.action as AuditLogAction)}>{log.action}</Badge>
                                            </TableCell>
                                            <TableCell className="text-muted-foreground">{log.details}</TableCell>
                                        </TableRow>
                                    ))
                                ) : (
                                    <TableRow>
                                        <TableCell colSpan={5} className="h-24 text-center">
                                            Nenhum registro encontrado. Realize ações no sistema para gerar logs.
                                        </TableCell>
                                    </TableRow>
                                )}
                            </TableBody>
                        </Table>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
