
import type { Servico } from '@/types/servico';

export const defaultServices: Omit<Servico, 'id'>[] = [
    { codigo: '1.01', descricao: 'Análise e desenvolvimento de sistemas.', valorPadrao: 1 },
    { codigo: '1.02', descricao: 'Programação.', valorPadrao: 1 },
    { codigo: '1.03', descricao: 'Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres.', valorPadrao: 1 },
    { codigo: '1.04', descricao: 'Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres.', valorPadrao: 1 },
    { codigo: '1.05', descricao: 'Licenciamento ou cessão de direito de uso de programas de computação.', valorPadrao: 1 },
    { codigo: '1.06', descricao: 'Assessoria e consultoria em informática.', valorPadrao: 1 },
    { codigo: '1.07', descricao: 'Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados.', valorPadrao: 1 },
    { codigo: '1.08', descricao: 'Planejamento, confecção, manutenção e atualização de páginas eletrônicas.', valorPadrao: 1 },
    { codigo: '1.09', descricao: 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos.', valorPadrao: 1 },
    { codigo: '2.01', descricao: 'Serviços de pesquisas e desenvolvimento de qualquer natureza.', valorPadrao: 1 },
    { codigo: '3.02', descricao: 'Cessão de direito de uso de marcas e de sinais de propaganda.', valorPadrao: 1 },
    { codigo: '3.03', descricao: 'Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas, estádios, ginásios, auditórios, casas de espetáculos, parques de diversões, canchas e congêneres.', valorPadrao: 1 },
    { codigo: '3.04', descricao: 'Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza.', valorPadrao: 1 },
    { codigo: '3.05', descricao: 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', valorPadrao: 1 },
    { codigo: '4.01', descricao: 'Medicina e biomedicina.', valorPadrao: 1 },
    { codigo: '4.02', descricao: 'Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres.', valorPadrao: 1 },
    { codigo: '4.03', descricao: 'Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres.', valorPadrao: 1 },
    { codigo: '4.04', descricao: 'Instrumentação cirúrgica.', valorPadrao: 1 },
    { codigo: '4.05', descricao: 'Acupuntura.', valorPadrao: 1 },
    { codigo: '4.06', descricao: 'Enfermagem, inclusive serviços auxiliares.', valorPadrao: 1 },
    { codigo: '4.07', descricao: 'Serviços farmacêuticos.', valorPadrao: 1 },
    { codigo: '4.08', descricao: 'Terapia ocupacional, fisioterapia e fonoaudiologia.', valorPadrao: 1 },
    { codigo: '4.09', descricao: 'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental.', valorPadrao: 1 },
    { codigo: '4.10', descricao: 'Nutrição.', valorPadrao: 1 },
    { codigo: '4.11', descricao: 'Obstetrícia.', valorPadrao: 1 },
    { codigo: '4.12', descricao: 'Odontologia.', valorPadrao: 1 },
    { codigo: '4.13', descricao: 'Ortóptica.', valorPadrao: 1 },
    { codigo: '4.14', descricao: 'Próteses sob encomenda.', valorPadrao: 1 },
    { codigo: '4.15', descricao: 'Psicanálise.', valorPadrao: 1 },
    { codigo: '4.16', descricao: 'Psicologia.', valorPadrao: 1 },
    { codigo: '4.17', descricao: 'Casas de repouso e de recuperação, creches, asilos e congêneres.', valorPadrao: 1 },
    { codigo: '4.18', descricao: 'Inseminação artificial, fertilização in vitro e congêneres.', valorPadrao: 1 },
    { codigo: '4.19', descricao: 'Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres.', valorPadrao: 1 },
    { codigo: '4.20', descricao: 'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie.', valorPadrao: 1 },
    { codigo: '4.21', descricao: 'Unidade de atendimento, assistência ou tratamento móvel e congêneres.', valorPadrao: 1 },
    { codigo: '4.22', descricao: 'Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres.', valorPadrao: 1 },
    { codigo: '4.23', descricao: 'Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário.', valorPadrao: 1 },
    { codigo: '5.01', descricao: 'Medicina veterinária e zootecnia.', valorPadrao: 1 },
    { codigo: '5.02', descricao: 'Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária.', valorPadrao: 1 },
    { codigo: '5.03', descricao: 'Laboratórios de análise na área veterinária.', valorPadrao: 1 },
    { codigo: '5.04', descricao: 'Inseminação artificial, fertilização in vitro e congêneres.', valorPadrao: 1 },
    { codigo: '5.05', descricao: 'Bancos de sangue e de órgãos e congêneres.', valorPadrao: 1 },
    { codigo: '5.06', descricao: 'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie.', valorPadrao: 1 },
    { codigo: '5.07', descricao: 'Unidade de atendimento, assistência ou tratamento móvel e congêneres.', valorPadrao: 1 },
    { codigo: '5.08', descricao: 'Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres.', valorPadrao: 1 },
    { codigo: '5.09', descricao: 'Planos de atendimento e assistência médico-veterinária.', valorPadrao: 1 },
    { codigo: '6.01', descricao: 'Barbearia, cabeleireiros, manicuros, pedicuros e congêneres.', valorPadrao: 1 },
    { codigo: '6.02', descricao: 'Esteticistas, tratamento de pele, depilação e congêneres.', valorPadrao: 1 },
    { codigo: '6.03', descricao: 'Banhos, duchas, sauna, massagens e congêneres.', valorPadrao: 1 },
    { codigo: '6.04', descricao: 'Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas.', valorPadrao: 1 },
    { codigo: '6.05', descricao: 'Centros de emagrecimento, spa e congêneres.', valorPadrao: 1 },
    { codigo: '6.06', descricao: 'Aplicação de tatuagens, piercings e congêneres.', valorPadrao: 1 },
    { codigo: '7.01', descricao: 'Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres.', valorPadrao: 1 },
    { codigo: '7.02', descricao: 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', valorPadrao: 1 },
    { codigo: '7.03', descricao: 'Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia.', valorPadrao: 1 },
    { codigo: '7.04', descricao: 'Demolição.', valorPadrao: 1 },
    { codigo: '7.05', descricao: 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', valorPadrao: 1 },
    { codigo: '7.06', descricao: 'Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço.', valorPadrao: 1 },
    { codigo: '7.07', descricao: 'Recuperação, raspagem, polimento e lustração de pisos e congêneres.', valorPadrao: 1 },
    { codigo: '7.08', descricao: 'Calafetação.', valorPadrao: 1 },
    { codigo: '7.09', descricao: 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', valorPadrao: 1 },
    { codigo: '7.10', descricao: 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', valorPadrao: 1 },
    { codigo: '7.11', descricao: 'Decoração e jardinagem, inclusive corte e poda de árvores.', valorPadrao: 1 },
    { codigo: '7.12', descricao: 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', valorPadrao: 1 },
    { codigo: '7.13', descricao: 'Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres.', valorPadrao: 1 },
    { codigo: '7.16', descricao: 'Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal.', valorPadrao: 1 },
    { codigo: '7.17', descricao: 'Escoramento, contenção de encostas e serviços congêneres.', valorPadrao: 1 },
    { codigo: '7.18', descricao: 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', valorPadrao: 1 },
    { codigo: '7.19', descricao: 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', valorPadrao: 1 },
    { codigo: '7.20', descricao: 'Aerofotogrametria, cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres.', valorPadrao: 1 },
    { codigo: '7.21', descricao: 'Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais.', valorPadrao: 1 },
    { codigo: '7.22', descricao: 'Nucleação e bombardeamento de nuvens e congêneres.', valorPadrao: 1 },
    { codigo: '8.01', descricao: 'Ensino regular pré-escolar, fundamental, médio e superior.', valorPadrao: 1 },
    { codigo: '8.02', descricao: 'Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza.', valorPadrao: 1 },
    { codigo: '9.01', descricao: 'Hospedagem de qualquer natureza em hotéis, apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service, hotelaria marítima, motéis, pensões e congêneres.', valorPadrao: 1 },
    { codigo: '9.02', descricao: 'Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres.', valorPadrao: 1 },
    { codigo: '9.03', descricao: 'Guias de turismo.', valorPadrao: 1 },
    { codigo: '10.01', descricao: 'Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, de planos de saúde e de planos de previdência privada.', valorPadrao: 1 },
    { codigo: '10.02', descricao: 'Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer.', valorPadrao: 1 },
    { codigo: '10.03', descricao: 'Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária.', valorPadrao: 1 },
    { codigo: '10.04', descricao: 'Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), de franquia (franchising) e de faturização (factoring).', valorPadrao: 1 },
    { codigo: '10.05', descricao: 'Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens.', valorPadrao: 1 },
    { codigo: '10.06', descricao: 'Agenciamento marítimo.', valorPadrao: 1 },
    { codigo: '10.07', descricao: 'Agenciamento de notícias.', valorPadrao: 1 },
    { codigo: '10.08', descricao: 'Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios.', valorPadrao: 1 },
    { codigo: '10.09', descricao: 'Representação de qualquer natureza, inclusive comercial.', valorPadrao: 1 },
    { codigo: '10.10', descricao: 'Distribuição de bens de terceiros.', valorPadrao: 1 },
    { codigo: '11.01', descricao: 'Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações.', valorPadrao: 1 },
    { codigo: '11.02', descricao: 'Vigilância, segurança ou monitoramento de bens, pessoas e semoventes.', valorPadrao: 1 },
    { codigo: '11.03', descricao: 'Escolta, inclusive de veículos e cargas.', valorPadrao: 1 },
    { codigo: '11.04', descricao: 'Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie.', valorPadrao: 1 },
    { codigo: '11.05', descricao: 'Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento.', valorPadrao: 1 },
    { codigo: '12.01', descricao: 'Espetáculos teatrais.', valorPadrao: 1 },
    { codigo: '12.02', descricao: 'Exibições cinematográficas.', valorPadrao: 1 },
    { codigo: '12.03', descricao: 'Espetáculos circenses.', valorPadrao: 1 },
    { codigo: '12.04', descricao: 'Programas de auditório.', valorPadrao: 1 },
    { codigo: '12.05', descricao: 'Parques de diversões, centros de lazer e congêneres.', valorPadrao: 1 },
    { codigo: '12.06', descricao: 'Boates, taxi-dancing e congêneres.', valorPadrao: 1 },
    { codigo: '12.07', descricao: 'Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres.', valorPadrao: 1 },
    { codigo: '12.08', descricao: 'Feiras, exposições, congressos e congêneres.', valorPadrao: 1 },
    { codigo: '12.09', descricao: 'Bilhares, boliches e diversões eletrônicas ou não.', valorPadrao: 1 },
    { codigo: '12.10', descricao: 'Corridas e competições de animais.', valorPadrao: 1 },
    { codigo: '12.11', descricao: 'Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador.', valorPadrao: 1 },
    { codigo: '12.12', descricao: 'Execução de música.', valorPadrao: 1 },
    { codigo: '12.13', descricao: 'Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres.', valorPadrao: 1 },
    { codigo: '12.14', descricao: 'Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo.', valorPadrao: 1 },
    { codigo: '12.15', descricao: 'Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres.', valorPadrao: 1 },
    { codigo: '12.16', descricao: 'Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres.', valorPadrao: 1 },
    { codigo: '12.17', descricao: 'Recreação e animação, inclusive em festas e eventos de qualquer natureza.', valorPadrao: 1 },
    { codigo: '13.02', descricao: 'Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres.', valorPadrao: 1 },
    { codigo: '13.03', descricao: 'Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres.', valorPadrao: 1 },
    { codigo: '13.04', descricao: 'Reprografia, microfilmagem e digitalização.', valorPadrao: 1 },
    { codigo: '13.05', descricao: 'Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia.', valorPadrao: 1 },
    { codigo: '14.01', descricao: 'Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto.', valorPadrao: 1 },
    { codigo: '14.02', descricao: 'Assistência técnica.', valorPadrao: 1 },
    { codigo: '14.03', descricao: 'Recondicionamento de motores.', valorPadrao: 1 },
    { codigo: '14.04', descricao: 'Recauchutagem ou regeneração de pneus.', valorPadrao: 1 },
    { codigo: '14.05', descricao: 'Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer.', valorPadrao: 1 },
    { codigo: '14.06', descricao: 'Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido.', valorPadrao: 1 },
    { codigo: '14.07', descricao: 'Colocação de molduras e congêneres.', valorPadrao: 1 },
    { codigo: '14.08', descricao: 'Encadernação, gravação e douração de livros, revistas e congêneres.', valorPadrao: 1 },
    { codigo: '14.09', descricao: 'Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento.', valorPadrao: 1 },
    { codigo: '14.10', descricao: 'Tinturaria e lavanderia.', valorPadrao: 1 },
    { codigo: '14.11', descricao: 'Tapeçaria e reforma de estofamentos em geral.', valorPadrao: 1 },
    { codigo: '14.12', descricao: 'Funilaria e lanternagem.', valorPadrao: 1 },
    { codigo: '14.13', descricao: 'Carpintaria e serralheria.', valorPadrao: 1 },
    { codigo: '14.14', descricao: 'Guincho intramunicipal, guindaste e içamento.', valorPadrao: 1 },
    { codigo: '15.01', descricao: 'Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres.', valorPadrao: 1 },
    { codigo: '15.02', descricao: 'Abertura de contas em geral, inclusive conta-corrente, conta de investimentos e aplicação e caderneta de poupança, no País e no exterior, bem como a manutenção das referidas contas ativas e inativas.', valorPadrao: 1 },
    { codigo: '15.03', descricao: 'Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral.', valorPadrao: 1 },
    { codigo: '15.04', descricao: 'Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres.', valorPadrao: 1 },
    { codigo: '15.05', descricao: 'Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão no Cadastro de Emitentes de Cheques sem Fundos.', valorPadrao: 1 },
    { codigo: '15.06', descricao: 'Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral.', valorPadrao: 1 },
    { codigo: '15.07', descricao: 'Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo.', valorPadrao: 1 },
    { codigo: '15.08', descricao: 'Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito.', valorPadrao: 1 },
    { codigo: '15.09', descricao: 'Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato.', valorPadrao: 1 },
    { codigo: '15.10', descricao: 'Serviços relacionados a cobranças, recebimentos ou pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros.', valorPadrao: 1 },
    { codigo: '15.11', descricao: 'Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados.', valorPadrao: 1 },
    { codigo: '15.12', descricao: 'Custódia em geral, inclusive de títulos e valores mobiliários.', valorPadrao: 1 },
    { codigo: '15.13', descricao: 'Serviços relacionados a operações de câmbio em geral.', valorPadrao: 1 },
    { codigo: '15.14', descricao: 'Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres.', valorPadrao: 1 },
    { codigo: '15.15', descricao: 'Compensação de cheques e títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer.', valorPadrao: 1 },
    { codigo: '15.16', descricao: 'Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo.', valorPadrao: 1 },
    { codigo: '15.17', descricao: 'Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão.', valorPadrao: 1 },
    { codigo: '15.18', descricao: 'Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel ou obra, análise técnica e jurídica.', valorPadrao: 1 },
    { codigo: '16.01', descricao: 'Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros.', valorPadrao: 1 },
    { codigo: '16.02', descricao: 'Outros serviços de transporte de natureza municipal.', valorPadrao: 1 },
    { codigo: '17.01', descricao: 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista.', valorPadrao: 1 },
    { codigo: '17.02', descricao: 'Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução.', valorPadrao: 1 },
    { codigo: '17.03', descricao: 'Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa.', valorPadrao: 1 },
    { codigo: '17.04', descricao: 'Recrutamento, agenciamento, seleção e colocação de mão-de-obra.', valorPadrao: 1 },
    { codigo: '17.05', descricao: 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', valorPadrao: 1 },
    { codigo: '17.06', descricao: 'Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade.', valorPadrao: 1 },
    { codigo: '17.08', descricao: 'Franquia (franchising).', valorPadrao: 1 },
    { codigo: '17.09', descricao: 'Perícias, laudos, exames técnicos e análises técnicas.', valorPadrao: 1 },
    { codigo: '17.10', descricao: 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', valorPadrao: 1 },
    { codigo: '17.11', descricao: 'Organização de festas e recepções; bufê.', valorPadrao: 1 },
    { codigo: '17.12', descricao: 'Administração em geral, inclusive de bens e negócios de terceiros.', valorPadrao: 1 },
    { codigo: '17.13', descricao: 'Leilão e congêneres.', valorPadrao: 1 },
    { codigo: '17.14', descricao: 'Advocacia.', valorPadrao: 1 },
    { codigo: '17.15', descricao: 'Arbitragem de qualquer espécie, inclusive jurídica.', valorPadrao: 1 },
    { codigo: '17.16', descricao: 'Auditoria.', valorPadrao: 1 },
    { codigo: '17.17', descricao: 'Análise de Organização e Métodos.', valorPadrao: 1 },
    { codigo: '17.18', descricao: 'Atuária e cálculos técnicos de qualquer natureza.', valorPadrao: 1 },
    { codigo: '17.19', descricao: 'Contabilidade, inclusive serviços técnicos e auxiliares.', valorPadrao: 1 },
    { codigo: '17.20', descricao: 'Consultoria e assessoria econômica ou financeira.', valorPadrao: 1 },
    { codigo: '17.21', descricao: 'Estatística.', valorPadrao: 1 },
    { codigo: '17.22', descricao: 'Cobrança em geral.', valorPadrao: 1 },
    { codigo: '17.23', descricao: 'Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar.', valorPadrao: 1 },
    { codigo: '17.24', descricao: 'Apresentação de palestras, conferências, seminários e congêneres.', valorPadrao: 1 },
    { codigo: '17.25', descricao: 'Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio.', valorPadrao: 1 },
    { codigo: '18.01', descricao: 'Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros.', valorPadrao: 1 },
    { codigo: '19.01', descricao: 'Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios.', valorPadrao: 1 },
    { codigo: '20.01', descricao: 'Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem.', valorPadrao: 1 },
    { codigo: '20.02', descricao: 'Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves.', valorPadrao: 1 },
    { codigo: '20.03', descricao: 'Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres.', valorPadrao: 1 },
    { codigo: '21.01', descricao: 'Serviços de registros públicos, cartorários e notariais.', valorPadrao: 1 },
    { codigo: '22.01', descricao: 'Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários.', valorPadrao: 1 },
    { codigo: '23.01', descricao: 'Serviços de programação e comunicação visual, desenho industrial e congêneres.', valorPadrao: 1 },
    { codigo: '24.01', descricao: 'Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres.', valorPadrao: 1 },
    { codigo: '25.01', descricao: 'Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico.', valorPadrao: 1 },
    { codigo: '25.02', descricao: 'Translado intramunicipal e cremação de corpos e partes de corpos cadavéricos.', valorPadrao: 1 },
    { codigo: '25.03', descricao: 'Planos ou convênio funerários.', valorPadrao: 1 },
    { codigo: '25.04', descricao: 'Manutenção e conservação de jazigos e cemitérios.', valorPadrao: 1 },
    { codigo: '25.05', descricao: 'Cessão de uso de espaços em cemitérios para sepultamento.', valorPadrao: 1 },
    { codigo: '26.01', descricao: 'Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores.', valorPadrao: 1 },
    { codigo: '27.01', descricao: 'Serviços de assistência social.', valorPadrao: 1 },
    { codigo: '28.01', descricao: 'Serviços de avaliação de bens e serviços de qualquer natureza.', valorPadrao: 1 },
    { codigo: '29.01', descricao: 'Serviços de biblioteconomia.', valorPadrao: 1 },
    { codigo: '30.01', descricao: 'Serviços de biologia, biotecnologia e química.', valorPadrao: 1 },
    { codigo: '31.01', descricao: 'Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres.', valorPadrao: 1 },
    { codigo: '32.01', descricao: 'Serviços de desenhos técnicos.', valorPadrao: 1 },
    { codigo: '33.01', descricao: 'Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres.', valorPadrao: 1 },
    { codigo: '34.01', descricao: 'Serviços de investigações particulares, detetives e congêneres.', valorPadrao: 1 },
    { codigo: '35.01', descricao: 'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas.', valorPadrao: 1 },
    { codigo: '36.01', descricao: 'Serviços de meteorologia.', valorPadrao: 1 },
    { codigo: '37.01', descricao: 'Serviços de artistas, atletas, modelos e manequins.', valorPadrao: 1 },
    { codigo: '38.01', descricao: 'Serviços de museologia.', valorPadrao: 1 },
    { codigo: '39.01', descricao: 'Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço).', valorPadrao: 1 },
    { codigo: '40.01', descricao: 'Obras de arte sob encomenda.', valorPadrao: 1 },
];
