/**
 * This file is the entry point for your Cloud Functions.
 * It has been automatically generated by the Firebase CLI.
 */

// We are not using this auto-generated file, as we are managing functions in our own directory structure.
// This file is kept to satisfy Firebase CLI deployment requirements.
// Our actual functions are located in the `lib/functions` directory, which is the compiled output of `src/functions`.

// To deploy functions, ensure your `firebase.json` points to the correct source directory:
// "functions": {
//   "source": "lib/functions",
//   "runtime": "nodejs20"
// }
